DROP DATABASE IF EXISTS adlister_db;
CREATE DATABASE adlister_db;
USE adlister_db;

CREATE TABLE users (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR (75) NOT NULL UNIQUE,
    email VARCHAR (100) NOT NULL UNIQUE,
    password VARCHAR (50) NOT NULL
);

CREATE TABLE ads (
    id INT UNSIGNED NOT NULL PRIMARy KEY AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL REFERENCES users(id),
    title VARCHAR(50) NOT NULL,
    description VARCHAR(200) NOT NULL
);

